> npm run db:seedorPro\tradenavigatorpro>
added 1 package, and audited 611 packages in 2s

178 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v6.9.0) to .\node_modules\@prisma\client in 90ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Interested in query caching in just a few lines of code? Try Accelerate today! https://pris.ly/tip-3-accelerate

Prisma schema loaded from prisma\schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  prisma\schema.prisma:10
   |
 9 |   provider = "postgresql"
10 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 6.9.0
npm error Missing script: "db:seed"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: C:\Users\NATUR\AppData\Local\npm-cache\_logs\2025-06-08T19_29_10_463Z-debug-0.log
PS F:\TradeNavigatorPro\tradenavigatorpro>